# -*- coding: utf-8 -*-
"""4110E002_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-qMbWnaKYU9ADeYr4BlYnxjlbQjgUcX
"""

x = input('Enter your name:')
print('Hello, ' + x)

a = eval(input("請輸入："))
a

b=a+1
b

print(10 + 5)

thislist = ["apple", "banana", "cherry"]
print(thislist)

thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

b = "Hello, World!"
print(b[2:5])

a = "Hello, World!"
print(a.lower())

myset = {"apple", "banana", "cherry"}
print(type(myset))

a = 200
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

year= eval(input("請輸入年"))

if ((year%400==0) or (year%4==0 and year%100!=0)):
  print("{0} 是閏年".format(year))
else:
  print("{0} 不是閏年".format(year))

x = float(1)     # x will be 1.0
y = float(2.8)   # y will be 2.8
z = float("3")   # z will be 3.0
w = float("4.2") # w will be 4.2

a = 33
b = 200

if b > a:
  print("b is greater than a")

a = "Hello"
b = "World"
c = a + " " + b
print(c)